version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - MONGO_URI=mongodb://mongo:27017/zhailau
      - PORT=8080
    depends_on:
      - mongo
    networks:
      - petstore-net

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "8081:80"
    depends_on:
      - backend
    networks:
      - petstore-net

  mongo:
    image: mongo:6
    ports:
      - "27018:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - petstore-net

  prometheus:
    image: prom/prometheus:latest
    ports:
      - "9091:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - ./alert_rules.yml:/etc/prometheus/alert_rules.yml
    networks:
      - petstore-net

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3001:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - grafana-data:/var/lib/grafana
    depends_on:
      - prometheus
    networks:
      - petstore-net

  node-exporter:
    image: prom/node-exporter:latest
    ports:
      - "9101:9100"
    networks:
      - petstore-net

volumes:
  mongo-data:
  grafana-data:

networks:
  petstore-net:
    driver: bridge